# Generated by Django 5.2.3 on 2025-06-10 13:17

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmedia",
            name="file",
            field=models.FileField(
                upload_to=apps.projects.models.project_media_upload_path
            ),
        ),
    ]
